name: cs415_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  firebase_database: ^10.0.7
  printing: ^5.10.0
  xml: ^6.3.0
  file_saver: 0.2.14
  intl: ^0.18.1
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  file_picker: ^10.0.0
  flutter_svg: ^2.0.9
  xml: ^6.3.0
  uuid: ^4.1.0 # For generating unique student IDs

  # Firebase Core & Firestore (for student registration)
  firebase_core: ^3.13.0
  cloud_firestore: 5.6.6

  # Optional: If you're also using real-time DB (can remove if not needed)
  firebase_database: ^11.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0         # Compatible with Dart 3.7+

flutter:
  uses-material-design: true
  
  assets:
    - assets/SAGEONS_2.xml
    - assets/STEMP.xml
    - assets/XMLs/programs.xml
    - assets/XMLs/courses.xml
    - assets/XMLs/courseAvailability.xml
    - assets/XMLs/prerequisities.xml
    - assets/XMLs/semType.xml
    - assets/XMLs/subprogrammes.xml
    - assets/semesters.xml
    - assets/campuses.xml
    - assets/images/header.png
    - assets/images/homepage.png
    - assets/images/student.png
    - assets/images/usp_logo.svg
  
