name: cs415_project
description: "A new Flutter project."

publish_to: 'none' # Remove this if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  file_picker: ^10.0.0
  flutter_svg: ^2.0.9
  xml: ^6.3.0
  uuid: ^4.1.0 # For generating unique student IDs
  pdf: ^3.6.0
  path_provider: ^2.0.8 # For saving the PDF file
  printing: ^5.12.0

  # Firebase Core & Firestore (for student registration)
  firebase_core: ^3.13.0
  cloud_firestore: 5.6.6

  # Optional: If you're also using real-time DB (can remove if not needed)
  firebase_database: ^11.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/courseAvailability.xml
    - assets/images/courses.xml
    - assets/images/prerequisities.xml
    - assets/images/programs.xml
    - assets/images/semType.xml
    - assets/images/subprogrammes.xml
    - assets/images/header.png
    - assets/images/usp_logo.svg
