name: cs415_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  provider: ^6.0.0
  shared_preferences: ^2.0.15  # Add shared_preferences here
  xml: ^6.3.0
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sbm_all_programmes.xml
    - assets/images/header.png
    - assets/images/usp_logo.svg
