name: cs415_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
<<<<<<< HEAD
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  xml: ^6.3.0
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8 
  flutter_svg: ^2.0.9
  provider: ^6.0.0
  shared_preferences: ^2.0.15
=======
  file_picker: ^9.2.1           # Latest stable as of now
  flutter:
    sdk: flutter
  xml: ^6.5.0                   # Latest stable
  url_launcher: ^6.3.1         # Updated from 6.1.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  provider: ^6.1.2              # Latest stable
  shared_preferences: ^2.2.2    # Latest stable
>>>>>>> 5ea62f08284e985d04e45eec10d5f13f97ac9262

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0         # Compatible with Dart 3.7+

flutter:
  uses-material-design: true
  
  assets:
    - assets/SAGEONS_2.xml
<<<<<<< HEAD
    - assets/STEMP.xml
=======
>>>>>>> 5ea62f08284e985d04e45eec10d5f13f97ac9262
    - assets/images/header.png
    - assets/images/usp_logo.svg
