name: cs415_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  printing: ^5.10.0
  xml: ^6.3.0
  file_saver: 0.2.14
  intl: ^0.18.1
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  provider: ^6.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0         # Compatible with Dart 3.7+

flutter:
  uses-material-design: true
  
  assets:
    - assets/SAGEONS_2.xml
    - assets/STEMP.xml
    - assets/STEMP/courses.xml
    - assets/STEMP/prerequisites.xml
    - assets/STEMP/courseAvailability.xml
    - assets/STEMP/courseTypes.xml
    - assets/STEMP/programs.xml
    - assets/STEMP/programTypes.xml
    - assets/STEMP/subPrograms.xml
    - assets/SOLASS/courses.xml
    - assets/SOLASS/prerequisites.xml
    - assets/SOLASS/courseAvailability.xml
    - assets/SOLASS/courseTypes.xml
    - assets/SOLASS/programs.xml
    - assets/SOLASS/programTypes.xml
    - assets/SOLASS/subPrograms.xml
    - assets/programLevels.xml
    - assets/semesters.xml
    - assets/campuses.xml
    - assets/images/header.png
    - assets/images/homepage.png
    - assets/images/student.png
    - assets/images/usp_logo.svg
